directories:
  - ".eslintcache"
  - "node_modules"

addons:
  apt:
    sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
    packages:
        - g++-7
        - gcc-7

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
 
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - make all

